#!/bin/bash

conFile="$2.conflit"
RacineA="$1"
RacineB="$2"

function print {
  l=$(egrep "^$RacineA $fichier/? .*$" $RacineB.synchro)
  Jperm=$(cut -f 3 -d ' ' <<< "$l")
  Jmodif=$(cut -f 4 -d ' ' <<< "$l")
  Jsize=$(cut -f 5 -d ' ' <<< "$l")
  Jidgroup=$(cut -f 6 -d ' ' <<< "$l")
  Jidowner=$(cut -f 7 -d ' ' <<< "$l")
  echo ""
  echo -e "\t\tRacineA/$line\tJournal\t\tRacineB/$line"
  echo -e "\t\t----------------------------------------------------"
  echo -e "\e[1mType:\e[0m\t\t |  $(file -b $RacineA$line)   |\t\t |  $(file -b $RacineB$(basename $RacineA)/$line)"
  echo -e "\e[1mpermission\e[0m:\t |  $(stat -c "%a" $RacineA$line)\t\t |  $Jperm\t\t |  $(stat -c "%a" $RacineB$(basename "$RacineA")/$line)"
  echo -e "\e[1mDate modication\e[0m: |  $(stat -c "%Y" $RacineA$line)\t |  $Jmodif\t |  $(stat -c "%Y" $RacineB$(basename "$RacineA")/$line)"
  echo -e "\e[1mTaille\e[0m:\t\t |  $(stat -c "%s" $RacineA$line)\t\t |  $Jsize\t |  $(stat -c "%s" $RacineB$(basename "$RacineA")/$line)"
  echo -e "\e[1mGroupe\e[0m:\t\t |  $(stat -c "%G" $RacineA$line)\t |  $Jidgroup\t |  $(stat -c "%G" $RacineB$(basename "$RacineA")/$line)"
  echo -e "\e[1mOwner\e[0m:\t\t |  $(stat -c "%U" $RacineA$line)\t |  $Jidowner\t |  $(stat -c "%U" $RacineB$(basename "$RacineA")/$line)"
  echo ""
}

while read -u 9 line; do
    options=("Option 1" "Option 2" "Option 3" "Quit")
    print
    select opt in "${options[@]}"; do
      error=0
      case $opt in
          "Option 1")
              echo "you chose choice 1"
              ;;
          "Option 2")
              echo "you chose choice 2"
              ;;
          "Option 3")
              echo "you chose choice 3"
              ;;
          "Quit")
              break
              ;;
          *) echo invalid option
              error=1
              ;;
      esac
      if [[ $error -eq 0 ]]; then
        if [[ true ]]; then #fichier egale
          print
          cat<<EOF
1) Option 1
2) Option 2
3) Option 3
4) Quit
EOF
        else
          break
        fi
      fi
    done
    clear
done 9< $conFile

rm $conFile
