#!/bin/bash

# $1 Dossier a "écrire"
# $2 RacineA
RacineOrigine=$2


for fichier in `ls $1`; do
  if [[ -f $1$fichier ]]; then
    # echo $1$fichier
    # echo `sed "s|^\(\$RacineOrigine\)\(.*\)$|\1 \2|" <<< "$1$fichier"`
    # stat -c "%a" $1$fichier
    # stat -c "%s" $1$fichier
    # stat -c "%g" $1$fichier
    # stat -c "%u" $1$fichier
    # #echo `sed "s|\/{.}+$||g" <<< "$fichier"`
    echo `sed "s|^\(\$RacineOrigine\)\(.*\)$|\1 \2|" <<< "$1$fichier"` `stat -c "%a" $1$fichier` `stat -c "%Y" $1$fichier` `stat -c "%s" $1$fichier` `stat -c "%g" $1$fichier` `stat -c "%u" $1$fichier` >> /.synchro
  elif [[ -d $1$fichier ]]; then
    # echo $1$fichier/
    # echo `sed "s|^\(\$RacineOrigine\)\(.*\/\)$|\1 \2|" <<< "$1$fichier/"`
    # stat -c "%a" $1$fichier/
    # stat -c "%s" $1$fichier/
    # stat -c "%g" $1$fichier/
    # stat -c "%u" $1$fichier/
    echo `sed "s|^\(\$RacineOrigine\)\(.*\/\)$|\1 \2|" <<< "$1$fichier/"` `stat -c "%a" $1$fichier/` `stat -c "%Y" $1$fichier/` `stat -c "%s" $1$fichier/` `stat -c "%g" $1$fichier/` `stat -c "%u" $1$fichier/`>> /.synchro
    ./ecrire_synchro $1$fichier/
  fi
done
