#!/bin/bash

# $1 Dossier a "écrire"
# $2 RacineA
# $3 RacineB/.synchro
RacineOrigine=$2


for fichier in  $1*; do
  # echo $fichier
  if [[ -f $fichier ]]; then
    # echo $fichier
    # echo `sed "s|^\(\$RacineOrigine\)\(.*\)$|\1 \2|" <<< "$fichier"`
    # stat -c "%a" $fichier
    # stat -c "%s" $fichier
    # stat -c "%G" $fichier
    # stat -c "%U" $fichier
    # #echo `sed "s|\/{.}+$||g" <<< "$fichier"`
    echo "`sed "s|^\(\$RacineOrigine\)\(.*\)$|\1 \2|" <<< "$fichier"` `stat -c '%a' $fichier` `stat -c '%Y' $fichier` `stat -c '%s' $fichier` `stat -c '%G' $fichier` `stat -c '%U' $fichier`" >> $3
  elif [[ -d $fichier ]]; then
    # echo $fichier/
    # echo `sed "s|^\(\$RacineOrigine\)\(.*\/\)$|\1 \2|" <<< "$fichier/"`
    # stat -c "%a" $fichier/
    # stat -c "%s" $fichier/
    # stat -c "%G" $fichier/
    # stat -c "%U" $fichier/
    echo "`sed "s|^\(\$RacineOrigine\)\(.*\/\)$|\1 \2|" <<< "$fichier/"` `stat -c '%a' $fichier/` `stat -c '%Y' $fichier/` `stat -c '%s' $fichier/` `stat -c '%G' $fichier/` `stat -c '%U' $fichier/`" >> $3
    "$(dirname $0)"/ecrire_synchro $fichier/ "$RacineOrigine" "$3"
  fi
done
