#!/bin/bash
conFile="$2.conflit"
racineA="$1"
racineB="$2"
contentDiff=1
metaDiff=1


while read line
do
	fileA = "$racineA$line"
	fileB = "$racineB$(basename $racineA)/$line"
	if [[ $(diff -q $fileA $fileB) ]] ; then #si les fichiers sont différents
		contentDiff=0 #on met un boolean à True
	fi
done < $conFile

if [[ contentDiff -eq 0 ]] ; then
	echo -e "Des conflits de contenu ont été detectés. Voulez vous régler ces conflits automatiquement? (remplacement par le fichier le plus récent)? [y/N]:"
	read rep
	if [[ $rep -eq 'y' ]] ; then
		while read line
		do
			fileA = "$racineA$line"
			fileB = "$racineB$(basename $racineA)/$line"
			if [[ $(stat -c "%Y" $fileA) -gt $(stat -c "%Y" $fileB) ]] ; then #si le fichier en racine A est plus récent que celui en racine B
				cp --preserve=all $fileA $fileB
			else
				cp --preserve=all $fileB $fileA
			fi
		done < $conFile
	#else
	#code pour mettre les balises dans les fichiers

	fi
else
echo "pas de conflit de contenu"
fi

while read line
do
	fileA = "$racineA$line"
	fileB = "$racineB$(basename $racineA)/$line"
	if [[ $(stat -c %Y%a%U%G $fileA) -ne $(stat -c %Y%a%U%G $fileB) ]] ; then #si les fichiers sont différents
		metaDiff=0 #on met un boolean à True
	fi
done < $conFile

#use touch for meta data?